### ISSUE TITLE
As a user, I want to be able to share the SDG pages on Facebook so that my networks of friends can also view the pages

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/unkt-sdg-plugin#6]
"As a user, I want to be able to share the SDG pages on Facebook so that my networks of friends can also view the pages"

Acceptance Criteria:

- [x]  When copying and pasting the link in a facebook post, a preview image is loaded.
- [x]  When copying and pasting the link in a facebook post, a page title is loaded.
- [x]  When copying and pasting the link in a facebook post, a page description is loaded.
- [x] The page title is custom to the goal page?
- [x]  The page description is custom to the description page?

**Comment by artaabdullahu** [comment]
@dafinaolluri  In every tasks who have  Acceptance Criteria items  add checkboxes, please.

**Comment by partini** [comment]
Sharing is working for twitter, but there are conflicts with SEO Plugins because they override current meta tags with the ones they generate.

<img width="1028" alt="screen shot 2017-03-21 at 10 30 26 am" src="https://cloud.githubusercontent.com/assets/7932995/24140768/766f9274-0e21-11e7-80aa-084792638a74.png">
