### ISSUE TITLE
As a user I want to be able to download the charts so that I can have it on my desktop

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/unkt-sdg-plugin#7]
"As a user I want  to be able to download the charts so that I can save it on my desktop" 

Acceptance Criteria:

- [x] The format should be: PNG, JPEG, PDF, SVG, CSV file

**Comment by artaabdullahu** [comment]
@partini please remove the first column because it is empty. This happening only when I downloaded indicators. For measurements is right.

<img width="1253" alt="screen shot 2017-03-14 at 4 36 04 pm" src="https://cloud.githubusercontent.com/assets/21961919/23908472/6e497472-08d4-11e7-9c97-de7a469291b9.png">
